// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CardTemplate', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CardTemplate', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    await driver.findElement(By.css("div:nth-child(1) > .sc-gicCDI > .sc-ezWOiH")).click()
    await driver.findElement(By.css(".sc-dmRaPn:nth-child(1) .sc-cxabCf")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".main-image > img")).click()
    await driver.findElement(By.css(".sc-hiMGwR")).click()
    await driver.findElement(By.css(".sc-hiMGwR")).click()
    await driver.findElement(By.css(".sc-hiMGwR")).click()
    await driver.findElement(By.css(".sc-hiMGwR")).click()
    await driver.findElement(By.css(".sc-olbas")).click()
  })
})
