// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('crearCuenta', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('crearCuenta', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    await driver.findElement(By.css("a:nth-child(1) > .sc-dkzDqf")).click()
    await driver.findElement(By.css("a:nth-child(2) > .sc-dkzDqf")).click()
    {
      const element = await driver.findElement(By.css("a:nth-child(2) > .sc-dkzDqf"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.name("nombre")).click()
    await driver.findElement(By.name("nombre")).sendKeys("Cecilia")
    await driver.findElement(By.name("apellido")).sendKeys("Abate")
    await driver.findElement(By.name("email")).sendKeys("m.cecilia.abate@gmail.com")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("mca_cuaco@hotmail.com")
    await driver.findElement(By.name("contrasenia")).click()
    await driver.findElement(By.name("contrasenia")).sendKeys("123456")
    await driver.findElement(By.name("confirmContra")).click()
    await driver.findElement(By.name("confirmContra")).sendKeys("123456")
    await driver.findElement(By.css(".sc-cCsOjp")).click()
    await driver.findElement(By.css(".sc-cCsOjp")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("mca_cuaco@hotmail.com")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("123456")
    await driver.findElement(By.css(".sc-cCsOjp")).click()
    await driver.findElement(By.css(".sc-dkzDqf")).click()
  })
})
