// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('administrador', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('administrador', async function() {
    await driver.get("http://ubicarfront.s3-website.us-east-2.amazonaws.com/")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    await driver.findElement(By.css("a:nth-child(1) > .sc-dkzDqf")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("m.cecilia.abate@gmail.com")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("123456")
    await driver.findElement(By.name("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.css("a > span")).click()
    await driver.findElement(By.name("title")).click()
    await driver.findElement(By.name("title")).sendKeys("un auto")
    await driver.findElement(By.css(".sc-gITdmR > label:nth-child(2) > .sc-brCFrO")).click()
    await driver.findElement(By.css(".sc-gITdmR > label:nth-child(2) > .sc-brCFrO")).sendKeys("este es un auto")
    await driver.findElement(By.css("label:nth-child(1) > select:nth-child(1)")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(1) > select:nth-child(1)"))
      await dropdown.findElement(By.xpath("//option[. = 'Lujosos , Autos de alta gama y mucho prestigio.']")).click()
    }
    await driver.findElement(By.css("label:nth-child(2) > select:nth-child(1)")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(2) > select:nth-child(1)"))
      await dropdown.findElement(By.xpath("//option[. = 'B1900 La Plata , Buenos Aires']")).click()
    }
    await driver.findElement(By.css(".sc-duzrYq > label:nth-child(1) > .sc-brCFrO")).click()
    await driver.findElement(By.css(".sc-duzrYq > label:nth-child(1) > .sc-brCFrO")).sendKeys("auto")
    await driver.findElement(By.name("url")).click()
    await driver.findElement(By.name("url")).sendKeys("1234")
    await driver.findElement(By.css("label:nth-child(1) > select:nth-child(2)")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(1) > select:nth-child(2)"))
      await dropdown.findElement(By.xpath("//option[. = 'Plazas : 5']")).click()
    }
    await driver.findElement(By.css("label:nth-child(2) > select:nth-child(2)")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(2) > select:nth-child(2)"))
      await dropdown.findElement(By.xpath("//option[. = 'Puertas : 5']")).click()
    }
    await driver.findElement(By.css("label:nth-child(3) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(3) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'Maletas : 4 grandes']")).click()
    }
    await driver.findElement(By.css("label:nth-child(4) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(4) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'Capacidad tanque : 45 Litros']")).click()
    }
    await driver.findElement(By.css("label:nth-child(5) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(5) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'Caja : Automática']")).click()
    }
    await driver.findElement(By.css("label:nth-child(6) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(6) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'Bolsas de Aire : 2']")).click()
    }
    await driver.findElement(By.css("label:nth-child(7) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(7) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'Bloqueo central : Sí']")).click()
    }
    await driver.findElement(By.css("label:nth-child(8) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(8) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'Bluetooth : No']")).click()
    }
    await driver.findElement(By.css("label:nth-child(9) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(9) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'Autonomía : 450 Km']")).click()
    }
    await driver.findElement(By.css("label:nth-child(10) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(10) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'GPS : Sí']")).click()
    }
    await driver.findElement(By.css("label:nth-child(11) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(11) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'Potencia : 300 Hp']")).click()
    }
    await driver.findElement(By.css("label:nth-child(12) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(12) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'Velocidad Max : 250 Km/h']")).click()
    }
    await driver.findElement(By.css("label:nth-child(13) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(13) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'Aceleracion a 100 Km/h : 2.4 Segundos']")).click()
    }
    await driver.findElement(By.css("label:nth-child(14) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(14) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'Capacidad del motor : 4000 CC']")).click()
    }
    await driver.findElement(By.css(".sc-ikjQzJ")).click()
    await driver.findElement(By.css(".sc-HzFiz > button")).click()
    await driver.findElement(By.css("div:nth-child(4) .sc-llJcti")).click()
    await driver.findElement(By.css(".sc-idiyUo:nth-child(8) .sc-fLlhyt")).click()
    await driver.findElement(By.css(".main-image > img")).click()
    await driver.findElement(By.css(".sc-fbPSWO")).click()
    await driver.findElement(By.css(".sc-fbPSWO")).click()
    await driver.findElement(By.css(".sc-fbPSWO")).click()
    await driver.findElement(By.css(".sc-fbPSWO")).click()
    await driver.findElement(By.css(".sc-ckMVTt")).click()
  })
})
