// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AdministradorTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void administrador() {
    driver.get("http://ubicarfront.s3-website.us-east-2.amazonaws.com/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.cssSelector("a:nth-child(1) > .sc-dkzDqf")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("m.cecilia.abate@gmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("123456");
    driver.findElement(By.name("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("a > span")).click();
    driver.findElement(By.name("title")).click();
    driver.findElement(By.name("title")).sendKeys("un auto");
    driver.findElement(By.cssSelector(".sc-gITdmR > label:nth-child(2) > .sc-brCFrO")).click();
    driver.findElement(By.cssSelector(".sc-gITdmR > label:nth-child(2) > .sc-brCFrO")).sendKeys("este es un auto");
    driver.findElement(By.cssSelector("label:nth-child(1) > select:nth-child(1)")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(1) > select:nth-child(1)"));
      dropdown.findElement(By.xpath("//option[. = 'Lujosos , Autos de alta gama y mucho prestigio.']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(2) > select:nth-child(1)")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(2) > select:nth-child(1)"));
      dropdown.findElement(By.xpath("//option[. = 'B1900 La Plata , Buenos Aires']")).click();
    }
    driver.findElement(By.cssSelector(".sc-duzrYq > label:nth-child(1) > .sc-brCFrO")).click();
    driver.findElement(By.cssSelector(".sc-duzrYq > label:nth-child(1) > .sc-brCFrO")).sendKeys("auto");
    driver.findElement(By.name("url")).click();
    driver.findElement(By.name("url")).sendKeys("1234");
    driver.findElement(By.cssSelector("label:nth-child(1) > select:nth-child(2)")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(1) > select:nth-child(2)"));
      dropdown.findElement(By.xpath("//option[. = 'Plazas : 5']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(2) > select:nth-child(2)")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(2) > select:nth-child(2)"));
      dropdown.findElement(By.xpath("//option[. = 'Puertas : 5']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(3) > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(3) > select"));
      dropdown.findElement(By.xpath("//option[. = 'Maletas : 4 grandes']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(4) > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(4) > select"));
      dropdown.findElement(By.xpath("//option[. = 'Capacidad tanque : 45 Litros']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(5) > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(5) > select"));
      dropdown.findElement(By.xpath("//option[. = 'Caja : Automática']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(6) > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(6) > select"));
      dropdown.findElement(By.xpath("//option[. = 'Bolsas de Aire : 2']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(7) > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(7) > select"));
      dropdown.findElement(By.xpath("//option[. = 'Bloqueo central : Sí']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(8) > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(8) > select"));
      dropdown.findElement(By.xpath("//option[. = 'Bluetooth : No']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(9) > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(9) > select"));
      dropdown.findElement(By.xpath("//option[. = 'Autonomía : 450 Km']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(10) > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(10) > select"));
      dropdown.findElement(By.xpath("//option[. = 'GPS : Sí']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(11) > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(11) > select"));
      dropdown.findElement(By.xpath("//option[. = 'Potencia : 300 Hp']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(12) > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(12) > select"));
      dropdown.findElement(By.xpath("//option[. = 'Velocidad Max : 250 Km/h']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(13) > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(13) > select"));
      dropdown.findElement(By.xpath("//option[. = 'Aceleracion a 100 Km/h : 2.4 Segundos']")).click();
    }
    driver.findElement(By.cssSelector("label:nth-child(14) > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector("label:nth-child(14) > select"));
      dropdown.findElement(By.xpath("//option[. = 'Capacidad del motor : 4000 CC']")).click();
    }
    driver.findElement(By.cssSelector(".sc-ikjQzJ")).click();
    driver.findElement(By.cssSelector(".sc-HzFiz > button")).click();
    driver.findElement(By.cssSelector("div:nth-child(4) .sc-llJcti")).click();
    driver.findElement(By.cssSelector(".sc-idiyUo:nth-child(8) .sc-fLlhyt")).click();
    driver.findElement(By.cssSelector(".main-image > img")).click();
    driver.findElement(By.cssSelector(".sc-fbPSWO")).click();
    driver.findElement(By.cssSelector(".sc-fbPSWO")).click();
    driver.findElement(By.cssSelector(".sc-fbPSWO")).click();
    driver.findElement(By.cssSelector(".sc-fbPSWO")).click();
    driver.findElement(By.cssSelector(".sc-ckMVTt")).click();
  }
}
