// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('craerUsuario', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('craerUsuario', async function() {
    await driver.get("http://ubicarfront.s3-website.us-east-2.amazonaws.com/")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    await driver.findElement(By.css("a:nth-child(2) > .sc-dkzDqf")).click()
    await driver.findElement(By.name("nombre")).click()
    await driver.findElement(By.name("nombre")).sendKeys("Maria")
    await driver.findElement(By.name("apellido")).click()
    await driver.findElement(By.name("apellido")).sendKeys("Cecilia")
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("unmail@mail.com")
    await driver.findElement(By.css("label:nth-child(4)")).click()
    await driver.findElement(By.name("contrasenia")).sendKeys("123456")
    await driver.findElement(By.name("confirmContra")).click()
    await driver.findElement(By.name("confirmContra")).sendKeys("123456")
    await driver.findElement(By.css(".sc-jIZahH")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("unmail@mail.com")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("123456")
    await driver.findElement(By.css(".sc-jIZahH")).click()
    await driver.findElement(By.css(".sc-bczRLJ")).click()
    await driver.findElement(By.css(".sc-dkzDqf")).click()
    await driver.findElement(By.css("a:nth-child(1) > .sc-dkzDqf")).click()
    await driver.findElement(By.css(".sc-gicCDI")).click()
  })
})
