// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('filtroHome', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('filtroHome', async function() {
    await driver.get("http://ubicarfront.s3-website.us-east-2.amazonaws.com/")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    await driver.executeScript("window.scrollTo(0,400)")
    await driver.executeScript("window.scrollTo(0,600)")
    await driver.findElement(By.css("div:nth-child(3) > .sc-cxabCf > .sc-llJcti")).click()
    await driver.findElement(By.css(".sc-hAZoDl:nth-child(1) > .sc-crXcEl")).click()
    {
      const dropdown = await driver.findElement(By.css(".sc-hAZoDl:nth-child(1) > .sc-crXcEl"))
      await dropdown.findElement(By.xpath("//option[. = 'Magallanes 7750, B7608 Mar del Plata , Buenos Aires']")).click()
    }
    await driver.findElement(By.css(".sc-hAZoDl:nth-child(2) > .sc-crXcEl")).click()
    {
      const dropdown = await driver.findElement(By.css(".sc-hAZoDl:nth-child(2) > .sc-crXcEl"))
      await dropdown.findElement(By.xpath("//option[. = 'Magallanes 7750, B7608 Mar del Plata , Buenos Aires']")).click()
    }
    await driver.findElement(By.css(".sc-evZas")).click()
    await driver.findElement(By.css(".sc-fLlhyt")).click()
  })
})
