// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('filtroCategoria/paginaProductoGaleria', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('filtroCategoria/paginaProductoGaleria', async function() {
    await driver.get("http://ubicarfront.s3-website.us-east-2.amazonaws.com/")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    await driver.executeScript("window.scrollTo(0,500)")
    await driver.findElement(By.css("div:nth-child(3) > .sc-cxabCf > .sc-llJcti")).click()
    await driver.findElement(By.css(".sc-fnykZs")).click()
    await driver.findElement(By.css(".sc-idiyUo:nth-child(2) .sc-fLlhyt")).click()
    await driver.findElement(By.css(".sc-ciZhAO")).click()
    await driver.findElement(By.css(".main-image > img")).click()
    await driver.findElement(By.css(".sc-fbPSWO")).click()
    await driver.findElement(By.css(".sc-fbPSWO")).click()
    await driver.findElement(By.css(".sc-fbPSWO")).click()
    await driver.findElement(By.css(".sc-fbPSWO")).click()
    await driver.findElement(By.css(".sc-ckMVTt")).click()
  })
})
