// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('reservaAnonimo', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('reservaAnonimo', async function() {
    await driver.get("http://ubicarfront.s3-website.us-east-2.amazonaws.com/")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    await driver.findElement(By.css("div:nth-child(4) .sc-llJcti")).click()
    await driver.findElement(By.css(".sc-idiyUo:nth-child(2) .sc-fLlhyt")).click()
    await driver.findElement(By.css(".sc-gSAPjG > button")).click()
    {
      const element = await driver.findElement(By.css(".sc-gSAPjG > button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".sc-jIAOiI > button:nth-child(2)")).click()
    await driver.findElement(By.css(".sc-gSAPjG > button")).click()
    {
      const element = await driver.findElement(By.css(".sc-gSAPjG > button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".sc-jIAOiI > button:nth-child(1)")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.css(".sc-jIZahH")).click()
    await driver.findElement(By.css(".sc-jIZahH")).click()
  })
})
