// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('reservaUsuario', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('reservaUsuario', async function() {
    await driver.get("http://ubicarfront.s3-website.us-east-2.amazonaws.com/")
    await driver.manage().window().setRect({ width: 1936, height: 1056 })
    await driver.findElement(By.css("a:nth-child(1) > .sc-dkzDqf")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("unmail@mail.com")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("123456")
    await driver.findElement(By.css(".sc-jIZahH")).click()
    await driver.findElement(By.css(".sc-bczRLJ")).click()
    await driver.executeScript("window.scrollTo(0,16)")
    await driver.findElement(By.css(".sc-idiyUo:nth-child(2) .sc-fLlhyt")).click()
    await driver.findElement(By.css(".arrow")).click()
    await driver.findElement(By.css(".sc-hAZoDl:nth-child(1) > .sc-crXcEl")).click()
    {
      const dropdown = await driver.findElement(By.css(".sc-hAZoDl:nth-child(1) > .sc-crXcEl"))
      await dropdown.findElement(By.xpath("//option[. = 'Magallanes 7750, B7608 Mar del Plata , Buenos Aires']")).click()
    }
    await driver.findElement(By.css(".sc-hAZoDl:nth-child(2) > .sc-crXcEl")).click()
    {
      const dropdown = await driver.findElement(By.css(".sc-hAZoDl:nth-child(2) > .sc-crXcEl"))
      await dropdown.findElement(By.xpath("//option[. = 'B1900 La Plata , Buenos Aires']")).click()
    }
    await driver.findElement(By.css(".sc-evZas")).click()
    await driver.findElement(By.css(".sc-idiyUo:nth-child(2) .sc-fLlhyt")).click()
    await driver.findElement(By.css(".sc-gSAPjG > button")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.name("ciudad")).click()
    await driver.findElement(By.name("ciudad")).sendKeys("Olavarría")
    await driver.findElement(By.css(".react-datepicker__day--selected")).click()
    await driver.findElement(By.css(".react-datepicker__day--024:nth-child(7)")).click()
    await driver.findElement(By.css("label:nth-child(2) > .form-control")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(2) > .form-control"))
      await dropdown.findElement(By.xpath("//option[. = '02:00 AM']")).click()
    }
    await driver.findElement(By.css("label:nth-child(3) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(3) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'CABA , CABA']")).click()
    }
    await driver.findElement(By.css("label:nth-child(4) > .form-control")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(4) > .form-control"))
      await dropdown.findElement(By.xpath("//option[. = '06:00 PM']")).click()
    }
    await driver.findElement(By.css("label:nth-child(5) > select")).click()
    {
      const dropdown = await driver.findElement(By.css("label:nth-child(5) > select"))
      await dropdown.findElement(By.xpath("//option[. = 'CABA , CABA']")).click()
    }
    await driver.findElement(By.css(".sc-jQHtVU")).click()
    await driver.findElement(By.css("button:nth-child(4)")).click()
    await driver.findElement(By.css(".sc-dkzDqf")).click()
  })
})
